
# Netlify configuration file

# Headers to ensure documents can be downloaded correctly
[[headers]]
  for = "/documents/*"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Access-Control-Allow-Origin = "*"

# Handle redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
